# Generated by Django 2.2.2 on 2019-09-28 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_metaglossario', '0002_auto_20190928_1043'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='glossary_entry',
            options={'ordering': ['-Admin_approval_switch', 'Lemma', 'Id_statico_entry']},
        ),
    ]
