# Generated by Django 2.2.2 on 2019-10-07 10:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_metaglossario', '0003_auto_20190928_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='glossary_entry',
            name='Commento_entry',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='glossary_entry',
            name='Data_inserimento_entry',
            field=models.DateField(default=datetime.date(2019, 10, 7)),
        ),
    ]
