# Generated by Django 2.2.2 on 2019-10-16 15:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_metaglossario', '0005_auto_20191014_1235'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='glossary_entry',
            options={'ordering': ['Admin_approval_switch', 'Lemma', 'Data_inserimento_entry', 'Id_statico_entry']},
        ),
        migrations.AlterField(
            model_name='glossary_entry',
            name='Data_inserimento_entry',
            field=models.DateField(default=datetime.date(2019, 10, 16)),
        ),
    ]
