# Generated by Django 2.2.2 on 2019-10-17 14:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_metaglossario', '0006_auto_20191016_1725'),
    ]

    operations = [
        migrations.CreateModel(
            name='glossary_file',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Glossary_file', models.FileField(upload_to='uploaded_files/')),
                ('Data_inserimento_glossary', models.DateField(default=datetime.date(2019, 10, 17))),
            ],
            options={
                'ordering': ['Data_inserimento_glossary', 'Glossary_file'],
            },
        ),
        migrations.AlterField(
            model_name='glossary_entry',
            name='Data_inserimento_entry',
            field=models.DateField(default=datetime.date(2019, 10, 17)),
        ),
    ]
