# Generated by Django 2.2.2 on 2019-10-17 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_metaglossario', '0007_auto_20191017_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glossary_file',
            name='Glossary_file',
            field=models.FileField(upload_to='uploaded_glossaries/'),
        ),
    ]
