# Generated by Django 2.2.2 on 2019-10-23 15:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_metaglossario', '0009_auto_20191021_1728'),
    ]

    operations = [
        migrations.CreateModel(
            name='acquired_terminology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Lemma', models.CharField(blank=True, max_length=256, null=True)),
                ('Acronimo', models.CharField(blank=True, max_length=25, null=True)),
                ('Definizione', models.TextField(blank=True, null=True)),
                ('Ambito_riferimento', models.CharField(blank=True, max_length=256, null=True)),
                ('Autore_definizione', models.CharField(blank=True, max_length=256, null=True)),
                ('Posizione_definizione', models.CharField(blank=True, max_length=256, null=True)),
                ('Url_definizione', models.URLField(blank=True, max_length=400, null=True)),
                ('Titolo_documento_fonte', models.CharField(blank=True, max_length=256, null=True)),
                ('Autore_documento_fonte', models.CharField(blank=True, max_length=256, null=True)),
                ('Host_documento_fonte', models.CharField(blank=True, max_length=256, null=True)),
                ('Url_documento_fonte', models.URLField(blank=True, max_length=400, null=True)),
                ('Commento_entry', models.TextField(blank=True, null=True)),
                ('Data_inserimento_entry', models.DateField(default=datetime.date(2019, 10, 23))),
                ('Id_statico_entry', models.CharField(default='ITCH00000', max_length=256)),
                ('Admin_approval_switch', models.CharField(choices=[('show', 'show'), ('hide', 'hide')], default=('hide', 'hide'), max_length=30)),
            ],
            options={
                'ordering': ['Admin_approval_switch', 'Lemma', 'Data_inserimento_entry', 'Id_statico_entry'],
            },
        ),
        migrations.AlterField(
            model_name='glossary_entry',
            name='Acronimo',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='glossary_entry',
            name='Autore_definizione',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='glossary_entry',
            name='Autore_documento_fonte',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='glossary_entry',
            name='Data_inserimento_entry',
            field=models.DateField(default=datetime.date(2019, 10, 23)),
        ),
        migrations.AlterField(
            model_name='glossary_entry',
            name='Host_documento_fonte',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='glossary_entry',
            name='Posizione_definizione',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='glossary_entry',
            name='Titolo_documento_fonte',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='glossary_file',
            name='Data_inserimento_glossary',
            field=models.DateField(default=datetime.date(2019, 10, 23)),
        ),
    ]
