# Generated by Django 2.2.2 on 2019-11-04 10:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_metaglossario', '0010_auto_20191023_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acquired_terminology',
            name='Data_inserimento_entry',
            field=models.DateField(default=datetime.date(2019, 11, 4)),
        ),
        migrations.AlterField(
            model_name='glossary_entry',
            name='Acronimo',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='glossary_entry',
            name='Data_inserimento_entry',
            field=models.DateField(default=datetime.date(2019, 11, 4)),
        ),
        migrations.AlterField(
            model_name='glossary_file',
            name='Data_inserimento_glossary',
            field=models.DateField(default=datetime.date(2019, 11, 4)),
        ),
    ]
