# Generated by Django 2.2.2 on 2019-11-06 14:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_metaglossario', '0011_auto_20191104_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acquired_terminology',
            name='Autore_definizione',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='acquired_terminology',
            name='Autore_documento_fonte',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='acquired_terminology',
            name='Data_inserimento_entry',
            field=models.DateField(default=datetime.date(2019, 11, 6)),
        ),
        migrations.AlterField(
            model_name='acquired_terminology',
            name='Host_documento_fonte',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='acquired_terminology',
            name='Posizione_definizione',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='acquired_terminology',
            name='Titolo_documento_fonte',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='glossary_entry',
            name='Data_inserimento_entry',
            field=models.DateField(default=datetime.date(2019, 11, 6)),
        ),
        migrations.AlterField(
            model_name='glossary_file',
            name='Data_inserimento_glossary',
            field=models.DateField(default=datetime.date(2019, 11, 6)),
        ),
    ]
