# Generated by Django 2.2.2 on 2019-11-25 09:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_metaglossario', '0017_auto_20191124_1824'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='is_Commento_entry_of',
            new_name='model_is_Acronimo_of',
        ),
        migrations.RenameModel(
            old_name='is_Host_documento_fonte_of',
            new_name='model_is_Admin_approval_switch_of',
        ),
        migrations.RenameModel(
            old_name='is_Autore_definizione_of',
            new_name='model_is_Ambito_riferimento_of',
        ),
        migrations.RenameModel(
            old_name='is_Data_inserimento_entry_of',
            new_name='model_is_Autore_definizione_of',
        ),
        migrations.RenameModel(
            old_name='is_Url_documento_fonte_of',
            new_name='model_is_Autore_documento_fonte_of',
        ),
        migrations.RenameModel(
            old_name='is_Lemma_of',
            new_name='model_is_Commento_entry_of',
        ),
        migrations.RenameModel(
            old_name='is_Admin_approval_switch_of',
            new_name='model_is_Data_inserimento_entry_of',
        ),
        migrations.RenameModel(
            old_name='is_Acronimo_of',
            new_name='model_is_Host_documento_fonte_of',
        ),
        migrations.RenameModel(
            old_name='is_Url_definizione_of',
            new_name='model_is_Id_statico_entry_of',
        ),
        migrations.RenameModel(
            old_name='is_Posizione_definizione_of',
            new_name='model_is_Lemma_of',
        ),
        migrations.RenameModel(
            old_name='is_Id_statico_entry_of',
            new_name='model_is_Posizione_definizione_of',
        ),
        migrations.RenameModel(
            old_name='is_Ambito_riferimento_of',
            new_name='model_is_Url_definizione_of',
        ),
        migrations.RenameModel(
            old_name='is_Autore_documento_fonte_of',
            new_name='model_is_Url_documento_fonte_of',
        ),
        migrations.RenameModel(
            old_name='Things',
            new_name='model_Things',
        ),
        migrations.AlterField(
            model_name='acquired_terminology',
            name='Data_inserimento_entry',
            field=models.DateField(default=datetime.date(2019, 11, 25)),
        ),
        migrations.AlterField(
            model_name='displaying_terminology',
            name='Data_inserimento_entry',
            field=models.DateField(default=datetime.date(2019, 11, 25)),
        ),
        migrations.AlterField(
            model_name='glossary_entry',
            name='Data_inserimento_entry',
            field=models.DateField(default=datetime.date(2019, 11, 25)),
        ),
        migrations.AlterField(
            model_name='glossary_file',
            name='Data_inserimento_glossary',
            field=models.DateField(default=datetime.date(2019, 11, 25)),
        ),
        migrations.AlterField(
            model_name='prepared_terminology',
            name='Data_inserimento_entry',
            field=models.DateField(default=datetime.date(2019, 11, 25)),
        ),
    ]
