# Generated by Django 2.2.2 on 2019-11-25 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_metaglossario', '0018_auto_20191125_1029'),
    ]

    operations = [
        migrations.CreateModel(
            name='model_Things_2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID', models.CharField(blank=True, max_length=25, null=True)),
                ('Oggetto', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['ID', 'Oggetto'],
            },
        ),
        migrations.AlterField(
            model_name='model_is_acronimo_of',
            name='ID_oggetto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_metaglossario.model_Things_2'),
        ),
        migrations.AlterField(
            model_name='model_is_acronimo_of',
            name='ID_soggetto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_metaglossario.model_Things'),
        ),
        migrations.AlterField(
            model_name='model_is_admin_approval_switch_of',
            name='ID_oggetto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_metaglossario.model_Things_2'),
        ),
        migrations.AlterField(
            model_name='model_is_admin_approval_switch_of',
            name='ID_soggetto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_metaglossario.model_Things'),
        ),
        migrations.AlterField(
            model_name='model_is_ambito_riferimento_of',
            name='ID_oggetto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_metaglossario.model_Things_2'),
        ),
        migrations.AlterField(
            model_name='model_is_ambito_riferimento_of',
            name='ID_soggetto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_metaglossario.model_Things'),
        ),
        migrations.AlterField(
            model_name='model_is_autore_definizione_of',
            name='ID_oggetto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_metaglossario.model_Things_2'),
        ),
        migrations.AlterField(
            model_name='model_is_autore_definizione_of',
            name='ID_soggetto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_metaglossario.model_Things'),
        ),
        migrations.AlterField(
            model_name='model_is_autore_documento_fonte_of',
            name='ID_oggetto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_metaglossario.model_Things_2'),
        ),
        migrations.AlterField(
            model_name='model_is_autore_documento_fonte_of',
            name='ID_soggetto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_metaglossario.model_Things'),
        ),
        migrations.AlterField(
            model_name='model_is_commento_entry_of',
            name='ID_oggetto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_metaglossario.model_Things_2'),
        ),
        migrations.AlterField(
            model_name='model_is_commento_entry_of',
            name='ID_soggetto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_metaglossario.model_Things'),
        ),
        migrations.AlterField(
            model_name='model_is_data_inserimento_entry_of',
            name='ID_oggetto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_metaglossario.model_Things_2'),
        ),
        migrations.AlterField(
            model_name='model_is_data_inserimento_entry_of',
            name='ID_soggetto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_metaglossario.model_Things'),
        ),
        migrations.AlterField(
            model_name='model_is_host_documento_fonte_of',
            name='ID_oggetto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_metaglossario.model_Things_2'),
        ),
        migrations.AlterField(
            model_name='model_is_host_documento_fonte_of',
            name='ID_soggetto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_metaglossario.model_Things'),
        ),
        migrations.AlterField(
            model_name='model_is_id_statico_entry_of',
            name='ID_oggetto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_metaglossario.model_Things_2'),
        ),
        migrations.AlterField(
            model_name='model_is_id_statico_entry_of',
            name='ID_soggetto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_metaglossario.model_Things'),
        ),
        migrations.AlterField(
            model_name='model_is_lemma_of',
            name='ID_oggetto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_metaglossario.model_Things_2'),
        ),
        migrations.AlterField(
            model_name='model_is_lemma_of',
            name='ID_soggetto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_metaglossario.model_Things'),
        ),
        migrations.AlterField(
            model_name='model_is_posizione_definizione_of',
            name='ID_oggetto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_metaglossario.model_Things_2'),
        ),
        migrations.AlterField(
            model_name='model_is_posizione_definizione_of',
            name='ID_soggetto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_metaglossario.model_Things'),
        ),
        migrations.AlterField(
            model_name='model_is_url_definizione_of',
            name='ID_oggetto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_metaglossario.model_Things_2'),
        ),
        migrations.AlterField(
            model_name='model_is_url_definizione_of',
            name='ID_soggetto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_metaglossario.model_Things'),
        ),
        migrations.AlterField(
            model_name='model_is_url_documento_fonte_of',
            name='ID_oggetto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_metaglossario.model_Things_2'),
        ),
        migrations.AlterField(
            model_name='model_is_url_documento_fonte_of',
            name='ID_soggetto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_metaglossario.model_Things'),
        ),
    ]
