# Generated by Django 2.2.2 on 2019-11-25 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_metaglossario', '0020_auto_20191125_1615'),
    ]

    operations = [
        migrations.CreateModel(
            name='model_Things_2',
            fields=[
                ('ID', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('Oggetto', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['ID', 'Oggetto'],
            },
        ),
    ]
