# Generated by Django 2.2.2 on 2019-11-25 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_metaglossario', '0021_model_things_2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='model_Things_2',
        ),
    ]
