# Generated by Django 2.2.2 on 2019-11-25 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_metaglossario', '0022_delete_model_things_2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='displaying_terminology',
        ),
    ]
