# Generated by Django 2.2.2 on 2019-11-28 16:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_metaglossario', '0024_model_is_titolo_documento_fonte_of'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acquired_terminology',
            name='Data_inserimento_entry',
            field=models.DateField(default=datetime.date(2019, 11, 28)),
        ),
        migrations.AlterField(
            model_name='glossary_entry',
            name='Data_inserimento_entry',
            field=models.DateField(default=datetime.date(2019, 11, 28)),
        ),
        migrations.AlterField(
            model_name='glossary_file',
            name='Data_inserimento_glossary',
            field=models.DateField(default=datetime.date(2019, 11, 28)),
        ),
        migrations.AlterField(
            model_name='model_is_acronimo_of',
            name='ID_oggetto',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='model_is_acronimo_of',
            name='ID_soggetto',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='model_is_admin_approval_switch_of',
            name='ID_oggetto',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='model_is_admin_approval_switch_of',
            name='ID_soggetto',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='model_is_ambito_riferimento_of',
            name='ID_oggetto',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='model_is_ambito_riferimento_of',
            name='ID_soggetto',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='model_is_autore_definizione_of',
            name='ID_oggetto',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='model_is_autore_definizione_of',
            name='ID_soggetto',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='model_is_autore_documento_fonte_of',
            name='ID_oggetto',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='model_is_autore_documento_fonte_of',
            name='ID_soggetto',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='model_is_commento_entry_of',
            name='ID_oggetto',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='model_is_commento_entry_of',
            name='ID_soggetto',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='model_is_data_inserimento_entry_of',
            name='ID_oggetto',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='model_is_data_inserimento_entry_of',
            name='ID_soggetto',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='model_is_host_documento_fonte_of',
            name='ID_oggetto',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='model_is_host_documento_fonte_of',
            name='ID_soggetto',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='model_is_id_statico_entry_of',
            name='ID_oggetto',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='model_is_id_statico_entry_of',
            name='ID_soggetto',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='model_is_lemma_of',
            name='ID_oggetto',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='model_is_lemma_of',
            name='ID_soggetto',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='model_is_posizione_definizione_of',
            name='ID_oggetto',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='model_is_posizione_definizione_of',
            name='ID_soggetto',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='model_is_titolo_documento_fonte_of',
            name='ID_oggetto',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='model_is_titolo_documento_fonte_of',
            name='ID_soggetto',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='model_is_url_definizione_of',
            name='ID_oggetto',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='model_is_url_definizione_of',
            name='ID_soggetto',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='model_is_url_documento_fonte_of',
            name='ID_oggetto',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='model_is_url_documento_fonte_of',
            name='ID_soggetto',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='model_things',
            name='ID',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='prepared_terminology',
            name='Data_inserimento_entry',
            field=models.DateField(default=datetime.date(2019, 11, 28)),
        ),
        migrations.CreateModel(
            name='model_is_prova_of',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_oggetto', models.ForeignKey(max_length=10, on_delete=django.db.models.deletion.CASCADE, related_name='model_is_prova_of_as_oggetto', to='app_metaglossario.model_Things')),
                ('ID_soggetto', models.ForeignKey(max_length=10, on_delete=django.db.models.deletion.CASCADE, related_name='model_is_prova_of_as_soggetto', to='app_metaglossario.model_Things')),
            ],
            options={
                'ordering': ['ID_soggetto', 'ID_oggetto'],
            },
        ),
    ]
