# Generated by Django 2.2.2 on 2019-11-28 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_metaglossario', '0026_auto_20191128_1711'),
    ]

    operations = [
        migrations.DeleteModel(
            name='model_is_prova_of',
        ),
    ]
