# Generated by Django 2.2.2 on 2019-11-29 18:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_metaglossario', '0029_auto_20191129_1853'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='displaying_terminology',
            options={},
        ),
        migrations.RemoveField(
            model_name='displaying_terminology',
            name='Acronimo',
        ),
        migrations.AddField(
            model_name='displaying_terminology',
            name='Acronimo',
            field=models.ManyToManyField(blank=True, max_length=25, related_name='_displaying_terminology_Acronimo_+', to='app_metaglossario.displaying_terminology'),
        ),
        migrations.RemoveField(
            model_name='displaying_terminology',
            name='Admin_approval_switch',
        ),
        migrations.AddField(
            model_name='displaying_terminology',
            name='Admin_approval_switch',
            field=models.ManyToManyField(choices=[('show', 'show'), ('hide', 'hide')], default=('hide', 'hide'), max_length=30, related_name='_displaying_terminology_Admin_approval_switch_+', to='app_metaglossario.displaying_terminology'),
        ),
        migrations.RemoveField(
            model_name='displaying_terminology',
            name='Ambito_riferimento',
        ),
        migrations.AddField(
            model_name='displaying_terminology',
            name='Ambito_riferimento',
            field=models.ManyToManyField(blank=True, max_length=256, related_name='_displaying_terminology_Ambito_riferimento_+', to='app_metaglossario.displaying_terminology'),
        ),
        migrations.RemoveField(
            model_name='displaying_terminology',
            name='Autore_definizione',
        ),
        migrations.AddField(
            model_name='displaying_terminology',
            name='Autore_definizione',
            field=models.ManyToManyField(blank=True, related_name='_displaying_terminology_Autore_definizione_+', to='app_metaglossario.displaying_terminology'),
        ),
        migrations.RemoveField(
            model_name='displaying_terminology',
            name='Autore_documento_fonte',
        ),
        migrations.AddField(
            model_name='displaying_terminology',
            name='Autore_documento_fonte',
            field=models.ManyToManyField(blank=True, related_name='_displaying_terminology_Autore_documento_fonte_+', to='app_metaglossario.displaying_terminology'),
        ),
        migrations.RemoveField(
            model_name='displaying_terminology',
            name='Commento_entry',
        ),
        migrations.AddField(
            model_name='displaying_terminology',
            name='Commento_entry',
            field=models.ManyToManyField(blank=True, related_name='_displaying_terminology_Commento_entry_+', to='app_metaglossario.displaying_terminology'),
        ),
        migrations.RemoveField(
            model_name='displaying_terminology',
            name='Data_inserimento_entry',
        ),
        migrations.AddField(
            model_name='displaying_terminology',
            name='Data_inserimento_entry',
            field=models.ManyToManyField(default=datetime.date(2019, 11, 29), related_name='_displaying_terminology_Data_inserimento_entry_+', to='app_metaglossario.displaying_terminology'),
        ),
        migrations.RemoveField(
            model_name='displaying_terminology',
            name='Definizione',
        ),
        migrations.AddField(
            model_name='displaying_terminology',
            name='Definizione',
            field=models.ManyToManyField(blank=True, related_name='_displaying_terminology_Definizione_+', to='app_metaglossario.displaying_terminology'),
        ),
        migrations.RemoveField(
            model_name='displaying_terminology',
            name='Host_documento_fonte',
        ),
        migrations.AddField(
            model_name='displaying_terminology',
            name='Host_documento_fonte',
            field=models.ManyToManyField(blank=True, related_name='_displaying_terminology_Host_documento_fonte_+', to='app_metaglossario.displaying_terminology'),
        ),
        migrations.RemoveField(
            model_name='displaying_terminology',
            name='Id_statico_entry',
        ),
        migrations.AddField(
            model_name='displaying_terminology',
            name='Id_statico_entry',
            field=models.ManyToManyField(default='ITCH00000', max_length=256, related_name='_displaying_terminology_Id_statico_entry_+', to='app_metaglossario.displaying_terminology'),
        ),
        migrations.RemoveField(
            model_name='displaying_terminology',
            name='Lemma',
        ),
        migrations.AddField(
            model_name='displaying_terminology',
            name='Lemma',
            field=models.ManyToManyField(blank=True, max_length=256, related_name='_displaying_terminology_Lemma_+', to='app_metaglossario.displaying_terminology'),
        ),
        migrations.RemoveField(
            model_name='displaying_terminology',
            name='Posizione_definizione',
        ),
        migrations.AddField(
            model_name='displaying_terminology',
            name='Posizione_definizione',
            field=models.ManyToManyField(blank=True, related_name='_displaying_terminology_Posizione_definizione_+', to='app_metaglossario.displaying_terminology'),
        ),
        migrations.RemoveField(
            model_name='displaying_terminology',
            name='Titolo_documento_fonte',
        ),
        migrations.AddField(
            model_name='displaying_terminology',
            name='Titolo_documento_fonte',
            field=models.ManyToManyField(blank=True, related_name='_displaying_terminology_Titolo_documento_fonte_+', to='app_metaglossario.displaying_terminology'),
        ),
        migrations.RemoveField(
            model_name='displaying_terminology',
            name='Url_definizione',
        ),
        migrations.AddField(
            model_name='displaying_terminology',
            name='Url_definizione',
            field=models.ManyToManyField(blank=True, max_length=400, related_name='_displaying_terminology_Url_definizione_+', to='app_metaglossario.displaying_terminology'),
        ),
        migrations.RemoveField(
            model_name='displaying_terminology',
            name='Url_documento_fonte',
        ),
        migrations.AddField(
            model_name='displaying_terminology',
            name='Url_documento_fonte',
            field=models.ManyToManyField(blank=True, max_length=400, related_name='_displaying_terminology_Url_documento_fonte_+', to='app_metaglossario.displaying_terminology'),
        ),
    ]
