# Generated by Django 2.2.2 on 2019-12-01 01:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_metaglossario', '0030_auto_20191129_1900'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='displaying_terminology',
            options={'ordering': ['Admin_approval_switch', 'Lemma', 'Data_inserimento_entry', 'Id_statico_entry']},
        ),
        migrations.AlterField(
            model_name='acquired_terminology',
            name='Data_inserimento_entry',
            field=models.DateField(default=datetime.date(2019, 12, 1)),
        ),
        migrations.RemoveField(
            model_name='displaying_terminology',
            name='Acronimo',
        ),
        migrations.AddField(
            model_name='displaying_terminology',
            name='Acronimo',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.RemoveField(
            model_name='displaying_terminology',
            name='Admin_approval_switch',
        ),
        migrations.AddField(
            model_name='displaying_terminology',
            name='Admin_approval_switch',
            field=models.CharField(choices=[('show', 'show'), ('hide', 'hide')], default=('hide', 'hide'), max_length=30),
        ),
        migrations.RemoveField(
            model_name='displaying_terminology',
            name='Ambito_riferimento',
        ),
        migrations.AddField(
            model_name='displaying_terminology',
            name='Ambito_riferimento',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.RemoveField(
            model_name='displaying_terminology',
            name='Autore_definizione',
        ),
        migrations.AddField(
            model_name='displaying_terminology',
            name='Autore_definizione',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='displaying_terminology',
            name='Autore_documento_fonte',
        ),
        migrations.AddField(
            model_name='displaying_terminology',
            name='Autore_documento_fonte',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='displaying_terminology',
            name='Commento_entry',
        ),
        migrations.AddField(
            model_name='displaying_terminology',
            name='Commento_entry',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='displaying_terminology',
            name='Data_inserimento_entry',
        ),
        migrations.AddField(
            model_name='displaying_terminology',
            name='Data_inserimento_entry',
            field=models.DateField(default=datetime.date(2019, 12, 1)),
        ),
        migrations.RemoveField(
            model_name='displaying_terminology',
            name='Definizione',
        ),
        migrations.AddField(
            model_name='displaying_terminology',
            name='Definizione',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='displaying_terminology',
            name='Host_documento_fonte',
        ),
        migrations.AddField(
            model_name='displaying_terminology',
            name='Host_documento_fonte',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='displaying_terminology',
            name='Id_statico_entry',
        ),
        migrations.AddField(
            model_name='displaying_terminology',
            name='Id_statico_entry',
            field=models.CharField(default='ITCH00000', max_length=256),
        ),
        migrations.RemoveField(
            model_name='displaying_terminology',
            name='Lemma',
        ),
        migrations.AddField(
            model_name='displaying_terminology',
            name='Lemma',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.RemoveField(
            model_name='displaying_terminology',
            name='Posizione_definizione',
        ),
        migrations.AddField(
            model_name='displaying_terminology',
            name='Posizione_definizione',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='displaying_terminology',
            name='Titolo_documento_fonte',
        ),
        migrations.AddField(
            model_name='displaying_terminology',
            name='Titolo_documento_fonte',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='displaying_terminology',
            name='Url_definizione',
        ),
        migrations.AddField(
            model_name='displaying_terminology',
            name='Url_definizione',
            field=models.URLField(blank=True, max_length=400, null=True),
        ),
        migrations.RemoveField(
            model_name='displaying_terminology',
            name='Url_documento_fonte',
        ),
        migrations.AddField(
            model_name='displaying_terminology',
            name='Url_documento_fonte',
            field=models.URLField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='glossary_entry',
            name='Data_inserimento_entry',
            field=models.DateField(default=datetime.date(2019, 12, 1)),
        ),
        migrations.AlterField(
            model_name='glossary_file',
            name='Data_inserimento_glossary',
            field=models.DateField(default=datetime.date(2019, 12, 1)),
        ),
        migrations.AlterField(
            model_name='prepared_terminology',
            name='Data_inserimento_entry',
            field=models.DateField(default=datetime.date(2019, 12, 1)),
        ),
        migrations.CreateModel(
            name='model_Titolo_documento_fonte',
            fields=[
                ('ID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Titolo_documento_fonte', models.TextField(blank=True, null=True)),
                ('Autore_documento_fonte', models.ManyToManyField(blank=True, null=True, related_name='_model_titolo_documento_fonte_Autore_documento_fonte_+', to='app_metaglossario.model_Titolo_documento_fonte')),
                ('Definizione', models.ManyToManyField(blank=True, null=True, related_name='_model_titolo_documento_fonte_Definizione_+', to='app_metaglossario.model_Titolo_documento_fonte')),
                ('Host_documento_fonte', models.ManyToManyField(blank=True, null=True, related_name='_model_titolo_documento_fonte_Host_documento_fonte_+', to='app_metaglossario.model_Titolo_documento_fonte')),
                ('Url_documento_fonte', models.ManyToManyField(blank=True, null=True, related_name='_model_titolo_documento_fonte_Url_documento_fonte_+', to='app_metaglossario.model_Titolo_documento_fonte')),
            ],
            options={
                'ordering': ['Titolo_documento_fonte', 'ID'],
            },
        ),
    ]
