# Generated by Django 2.2.2 on 2019-12-01 10:18

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_metaglossario', '0034_auto_20191201_0253'),
    ]

    operations = [
        migrations.CreateModel(
            name='model_Titolo_documento_fonte',
            fields=[
                ('ID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Titolo_documento_fonte', models.TextField(blank=True, null=True)),
                ('Url_documento_fonte', django.contrib.postgres.fields.ArrayField(base_field=models.URLField(max_length=400), blank=True, null=True, size=None)),
                ('Autore_documento_fonte', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None)),
                ('Host_documento_fonte', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None)),
                ('Definizione', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None)),
            ],
            options={
                'ordering': ['Titolo_documento_fonte', 'ID'],
            },
        ),
        migrations.CreateModel(
            name='model_Url_documento_fonte',
            fields=[
                ('ID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Url_documento_fonte', models.TextField(blank=True, null=True)),
                ('Titolo_documento_fonte', models.ManyToManyField(blank=True, null=True, to='app_metaglossario.model_Titolo_documento_fonte')),
            ],
            options={
                'ordering': ['Url_documento_fonte', 'ID'],
            },
        ),
        migrations.CreateModel(
            name='model_Host_documento_fonte',
            fields=[
                ('ID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Host_documento_fonte', models.TextField(blank=True, null=True)),
                ('Titolo_documento_fonte', models.ManyToManyField(blank=True, null=True, to='app_metaglossario.model_Titolo_documento_fonte')),
            ],
            options={
                'ordering': ['Host_documento_fonte', 'ID'],
            },
        ),
        migrations.CreateModel(
            name='model_Autore_documento_fonte',
            fields=[
                ('ID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Autore_documento_fonte', models.TextField(blank=True, null=True)),
                ('Titolo_documento_fonte', models.ManyToManyField(blank=True, null=True, to='app_metaglossario.model_Titolo_documento_fonte')),
            ],
            options={
                'ordering': ['Autore_documento_fonte', 'ID'],
            },
        ),
    ]
