# Generated by Django 2.2.2 on 2019-12-02 18:06

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_metaglossario', '0035_model_autore_documento_fonte_model_host_documento_fonte_model_titolo_documento_fonte_model_url_docum'),
    ]

    operations = [
        migrations.CreateModel(
            name='model_node',
            fields=[
                ('ID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Thing', models.TextField(blank=True, null=True)),
                ('Entita', models.CharField(blank=True, max_length=256, null=True)),
                ('connected_Lemma', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256), blank=True, null=True, size=None)),
                ('connected_Acronimo', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=25), blank=True, null=True, size=None)),
                ('connected_Definizione', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None)),
                ('connected_Ambito_riferimento', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256), blank=True, null=True, size=None)),
                ('connected_Autore_definizione', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None)),
                ('connected_Posizione_definizione', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None)),
                ('connected_Url_definizione', django.contrib.postgres.fields.ArrayField(base_field=models.URLField(max_length=400), blank=True, null=True, size=None)),
                ('connected_Titolo_documento_fonte', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None)),
                ('connected_Autore_documento_fonte', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None)),
                ('connected_Host_documento_fonte', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None)),
                ('connected_Url_documento_fonte', django.contrib.postgres.fields.ArrayField(base_field=models.URLField(max_length=400), blank=True, null=True, size=None)),
                ('connected_Commento_entry', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None)),
                ('connected_Data_inserimento_entry', django.contrib.postgres.fields.ArrayField(base_field=models.DateField(), default=datetime.date(2019, 12, 2), size=None)),
                ('connected_Id_statico_entry', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256), default='ITCH00000', size=None)),
                ('connected_Admin_approval_switch', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), size=None)),
            ],
            options={
                'ordering': ['Entita', 'Thing', 'ID'],
            },
        ),
        migrations.RemoveField(
            model_name='model_host_documento_fonte',
            name='Titolo_documento_fonte',
        ),
        migrations.RemoveField(
            model_name='model_url_documento_fonte',
            name='Titolo_documento_fonte',
        ),
        migrations.AlterField(
            model_name='acquired_terminology',
            name='Data_inserimento_entry',
            field=models.DateField(default=datetime.date(2019, 12, 2)),
        ),
        migrations.AlterField(
            model_name='displaying_terminology',
            name='Data_inserimento_entry',
            field=models.DateField(default=datetime.date(2019, 12, 2)),
        ),
        migrations.AlterField(
            model_name='glossary_entry',
            name='Data_inserimento_entry',
            field=models.DateField(default=datetime.date(2019, 12, 2)),
        ),
        migrations.AlterField(
            model_name='glossary_file',
            name='Data_inserimento_glossary',
            field=models.DateField(default=datetime.date(2019, 12, 2)),
        ),
        migrations.AlterField(
            model_name='prepared_terminology',
            name='Data_inserimento_entry',
            field=models.DateField(default=datetime.date(2019, 12, 2)),
        ),
        migrations.DeleteModel(
            name='model_Autore_documento_fonte',
        ),
        migrations.DeleteModel(
            name='model_Host_documento_fonte',
        ),
        migrations.DeleteModel(
            name='model_Titolo_documento_fonte',
        ),
        migrations.DeleteModel(
            name='model_Url_documento_fonte',
        ),
    ]
