# Generated by Django 2.2.2 on 2019-12-02 18:20

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_metaglossario', '0036_auto_20191202_1906'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='model_node',
            options={'ordering': ['Entita', 'centered_Thing', 'centered_ID']},
        ),
        migrations.RenameField(
            model_name='model_node',
            old_name='ID',
            new_name='centered_ID',
        ),
        migrations.RenameField(
            model_name='model_node',
            old_name='Thing',
            new_name='centered_Thing',
        ),
        migrations.AddField(
            model_name='model_node',
            name='connected_Acronimo_ID',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='model_node',
            name='connected_Admin_approval_switch_ID',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='model_node',
            name='connected_Ambito_riferimento_ID',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='model_node',
            name='connected_Autore_definizione_ID',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='model_node',
            name='connected_Autore_documento_fonte_ID',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='model_node',
            name='connected_Commento_entry_ID',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='model_node',
            name='connected_Data_inserimento_entry_ID',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='model_node',
            name='connected_Definizione_ID',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='model_node',
            name='connected_Host_documento_fonte_ID',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='model_node',
            name='connected_Id_statico_entry_ID',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='model_node',
            name='connected_Lemma_ID',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='model_node',
            name='connected_Posizione_definizione_ID',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='model_node',
            name='connected_Titolo_documento_fonte_ID',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='model_node',
            name='connected_Url_definizione_ID',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='model_node',
            name='connected_Url_documento_fonte_ID',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), blank=True, null=True, size=None),
        ),
    ]
