# Generated by Django 2.2.2 on 2019-12-03 10:46

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_metaglossario', '0037_auto_20191202_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acquired_terminology',
            name='Data_inserimento_entry',
            field=models.DateField(default=datetime.date(2019, 12, 3)),
        ),
        migrations.AlterField(
            model_name='displaying_terminology',
            name='Data_inserimento_entry',
            field=models.DateField(default=datetime.date(2019, 12, 3)),
        ),
        migrations.AlterField(
            model_name='glossary_entry',
            name='Data_inserimento_entry',
            field=models.DateField(default=datetime.date(2019, 12, 3)),
        ),
        migrations.AlterField(
            model_name='glossary_file',
            name='Data_inserimento_glossary',
            field=models.DateField(default=datetime.date(2019, 12, 3)),
        ),
        migrations.AlterField(
            model_name='model_node',
            name='connected_Data_inserimento_entry',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DateField(), default=datetime.date(2019, 12, 3), size=None),
        ),
        migrations.AlterField(
            model_name='prepared_terminology',
            name='Data_inserimento_entry',
            field=models.DateField(default=datetime.date(2019, 12, 3)),
        ),
    ]
