# Generated by Django 2.2.2 on 2019-12-03 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_metaglossario', '0038_auto_20191203_1146'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='model_node',
            options={'ordering': ['entita', 'centered_Thing', 'centered_ID']},
        ),
        migrations.RenameField(
            model_name='model_node',
            old_name='Entita',
            new_name='entita',
        ),
    ]
