# Generated by Django 2.2.2 on 2019-12-03 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_metaglossario', '0039_auto_20191203_1306'),
    ]

    operations = [
        migrations.DeleteModel(
            name='model_is_Acronimo_of',
        ),
        migrations.DeleteModel(
            name='model_is_Admin_approval_switch_of',
        ),
        migrations.DeleteModel(
            name='model_is_Ambito_riferimento_of',
        ),
        migrations.DeleteModel(
            name='model_is_Autore_definizione_of',
        ),
        migrations.DeleteModel(
            name='model_is_Autore_documento_fonte_of',
        ),
        migrations.DeleteModel(
            name='model_is_Commento_entry_of',
        ),
        migrations.DeleteModel(
            name='model_is_Data_inserimento_entry_of',
        ),
        migrations.DeleteModel(
            name='model_is_Host_documento_fonte_of',
        ),
        migrations.DeleteModel(
            name='model_is_Id_statico_entry_of',
        ),
        migrations.DeleteModel(
            name='model_is_Lemma_of',
        ),
        migrations.DeleteModel(
            name='model_is_Posizione_definizione_of',
        ),
        migrations.DeleteModel(
            name='model_is_Titolo_documento_fonte_of',
        ),
        migrations.DeleteModel(
            name='model_is_Url_definizione_of',
        ),
        migrations.DeleteModel(
            name='model_is_Url_documento_fonte_of',
        ),
    ]
