# Generated by Django 2.2.2 on 2019-12-03 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_metaglossario', '0040_auto_20191203_1312'),
    ]

    operations = [
        migrations.DeleteModel(
            name='model_Things',
        ),
    ]
