# Generated by Django 2.2.2 on 2019-12-03 13:05

import django.contrib.postgres.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_metaglossario', '0041_delete_model_things'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model_node',
            name='connected_Data_inserimento_entry',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DateField(default=django.utils.timezone.now), size=None),
        ),
    ]
