# Generated by Django 2.2.2 on 2019-12-03 13:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_metaglossario', '0042_auto_20191203_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acquired_terminology',
            name='Data_inserimento_entry',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='displaying_terminology',
            name='Data_inserimento_entry',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='glossary_entry',
            name='Data_inserimento_entry',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='glossary_file',
            name='Data_inserimento_glossary',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='prepared_terminology',
            name='Data_inserimento_entry',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
