# Generated by Django 2.2.2 on 2019-12-03 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_metaglossario', '0043_auto_20191203_1407'),
    ]

    operations = [
        migrations.CreateModel(
            name='model_is_Acronimo_of',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_soggetto', models.CharField(max_length=10)),
                ('ID_oggetto', models.CharField(max_length=10)),
            ],
            options={
                'ordering': ['ID_soggetto', 'ID_oggetto'],
            },
        ),
        migrations.CreateModel(
            name='model_is_Admin_approval_switch_of',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_soggetto', models.CharField(max_length=10)),
                ('ID_oggetto', models.CharField(max_length=10)),
            ],
            options={
                'ordering': ['ID_soggetto', 'ID_oggetto'],
            },
        ),
        migrations.CreateModel(
            name='model_is_Ambito_riferimento_of',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_soggetto', models.CharField(max_length=10)),
                ('ID_oggetto', models.CharField(max_length=10)),
            ],
            options={
                'ordering': ['ID_soggetto', 'ID_oggetto'],
            },
        ),
        migrations.CreateModel(
            name='model_is_Autore_definizione_of',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_soggetto', models.CharField(max_length=10)),
                ('ID_oggetto', models.CharField(max_length=10)),
            ],
            options={
                'ordering': ['ID_soggetto', 'ID_oggetto'],
            },
        ),
        migrations.CreateModel(
            name='model_is_Autore_documento_fonte_of',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_soggetto', models.CharField(max_length=10)),
                ('ID_oggetto', models.CharField(max_length=10)),
            ],
            options={
                'ordering': ['ID_soggetto', 'ID_oggetto'],
            },
        ),
        migrations.CreateModel(
            name='model_is_Commento_entry_of',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_soggetto', models.CharField(max_length=10)),
                ('ID_oggetto', models.CharField(max_length=10)),
            ],
            options={
                'ordering': ['ID_soggetto', 'ID_oggetto'],
            },
        ),
        migrations.CreateModel(
            name='model_is_Data_inserimento_entry_of',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_soggetto', models.CharField(max_length=10)),
                ('ID_oggetto', models.CharField(max_length=10)),
            ],
            options={
                'ordering': ['ID_soggetto', 'ID_oggetto'],
            },
        ),
        migrations.CreateModel(
            name='model_is_Host_documento_fonte_of',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_soggetto', models.CharField(max_length=10)),
                ('ID_oggetto', models.CharField(max_length=10)),
            ],
            options={
                'ordering': ['ID_soggetto', 'ID_oggetto'],
            },
        ),
        migrations.CreateModel(
            name='model_is_Id_statico_entry_of',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_soggetto', models.CharField(max_length=10)),
                ('ID_oggetto', models.CharField(max_length=10)),
            ],
            options={
                'ordering': ['ID_soggetto', 'ID_oggetto'],
            },
        ),
        migrations.CreateModel(
            name='model_is_Lemma_of',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_soggetto', models.CharField(max_length=10)),
                ('ID_oggetto', models.CharField(max_length=10)),
            ],
            options={
                'ordering': ['ID_soggetto', 'ID_oggetto'],
            },
        ),
        migrations.CreateModel(
            name='model_is_Posizione_definizione_of',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_soggetto', models.CharField(max_length=10)),
                ('ID_oggetto', models.CharField(max_length=10)),
            ],
            options={
                'ordering': ['ID_soggetto', 'ID_oggetto'],
            },
        ),
        migrations.CreateModel(
            name='model_is_Titolo_documento_fonte_of',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_soggetto', models.CharField(max_length=10)),
                ('ID_oggetto', models.CharField(max_length=10)),
            ],
            options={
                'ordering': ['ID_soggetto', 'ID_oggetto'],
            },
        ),
        migrations.CreateModel(
            name='model_is_Url_definizione_of',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_soggetto', models.CharField(max_length=10)),
                ('ID_oggetto', models.CharField(max_length=10)),
            ],
            options={
                'ordering': ['ID_soggetto', 'ID_oggetto'],
            },
        ),
        migrations.CreateModel(
            name='model_is_Url_documento_fonte_of',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_soggetto', models.CharField(max_length=10)),
                ('ID_oggetto', models.CharField(max_length=10)),
            ],
            options={
                'ordering': ['ID_soggetto', 'ID_oggetto'],
            },
        ),
        migrations.CreateModel(
            name='model_Things',
            fields=[
                ('ID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Oggetto', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['ID', 'Oggetto'],
            },
        ),
        migrations.DeleteModel(
            name='model_node',
        ),
    ]
