# Generated by Django 2.2.2 on 2019-12-12 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_metaglossario', '0044_auto_20191203_1707'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='model_things',
            options={'ordering': ['ID_Thing', 'Thing']},
        ),
        migrations.RenameField(
            model_name='model_things',
            old_name='ID',
            new_name='ID_Thing',
        ),
        migrations.RenameField(
            model_name='model_things',
            old_name='Oggetto',
            new_name='Thing',
        ),
    ]
