# Generated by Django 2.2.2 on 2019-12-12 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_metaglossario', '0045_auto_20191212_1235'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='model_is_acronimo_of',
            options={'ordering': ['id_soggetto', 'id_oggetto']},
        ),
        migrations.AlterModelOptions(
            name='model_is_admin_approval_switch_of',
            options={'ordering': ['id_soggetto', 'id_oggetto']},
        ),
        migrations.AlterModelOptions(
            name='model_is_ambito_riferimento_of',
            options={'ordering': ['id_soggetto', 'id_oggetto']},
        ),
        migrations.AlterModelOptions(
            name='model_is_autore_definizione_of',
            options={'ordering': ['id_soggetto', 'id_oggetto']},
        ),
        migrations.AlterModelOptions(
            name='model_is_autore_documento_fonte_of',
            options={'ordering': ['id_soggetto', 'id_oggetto']},
        ),
        migrations.AlterModelOptions(
            name='model_is_commento_entry_of',
            options={'ordering': ['id_soggetto', 'id_oggetto']},
        ),
        migrations.AlterModelOptions(
            name='model_is_data_inserimento_entry_of',
            options={'ordering': ['id_soggetto', 'id_oggetto']},
        ),
        migrations.AlterModelOptions(
            name='model_is_host_documento_fonte_of',
            options={'ordering': ['id_soggetto', 'id_oggetto']},
        ),
        migrations.AlterModelOptions(
            name='model_is_id_statico_entry_of',
            options={'ordering': ['id_soggetto', 'id_oggetto']},
        ),
        migrations.AlterModelOptions(
            name='model_is_lemma_of',
            options={'ordering': ['id_soggetto', 'id_oggetto']},
        ),
        migrations.AlterModelOptions(
            name='model_is_posizione_definizione_of',
            options={'ordering': ['id_soggetto', 'id_oggetto']},
        ),
        migrations.AlterModelOptions(
            name='model_is_titolo_documento_fonte_of',
            options={'ordering': ['id_soggetto', 'id_oggetto']},
        ),
        migrations.AlterModelOptions(
            name='model_is_url_definizione_of',
            options={'ordering': ['id_soggetto', 'id_oggetto']},
        ),
        migrations.AlterModelOptions(
            name='model_is_url_documento_fonte_of',
            options={'ordering': ['id_soggetto', 'id_oggetto']},
        ),
        migrations.AlterModelOptions(
            name='model_things',
            options={'ordering': ['id_thing', 'thing']},
        ),
        migrations.RenameField(
            model_name='model_is_acronimo_of',
            old_name='ID_oggetto',
            new_name='id_oggetto',
        ),
        migrations.RenameField(
            model_name='model_is_acronimo_of',
            old_name='ID_soggetto',
            new_name='id_soggetto',
        ),
        migrations.RenameField(
            model_name='model_is_admin_approval_switch_of',
            old_name='ID_oggetto',
            new_name='id_oggetto',
        ),
        migrations.RenameField(
            model_name='model_is_admin_approval_switch_of',
            old_name='ID_soggetto',
            new_name='id_soggetto',
        ),
        migrations.RenameField(
            model_name='model_is_ambito_riferimento_of',
            old_name='ID_oggetto',
            new_name='id_oggetto',
        ),
        migrations.RenameField(
            model_name='model_is_ambito_riferimento_of',
            old_name='ID_soggetto',
            new_name='id_soggetto',
        ),
        migrations.RenameField(
            model_name='model_is_autore_definizione_of',
            old_name='ID_oggetto',
            new_name='id_oggetto',
        ),
        migrations.RenameField(
            model_name='model_is_autore_definizione_of',
            old_name='ID_soggetto',
            new_name='id_soggetto',
        ),
        migrations.RenameField(
            model_name='model_is_autore_documento_fonte_of',
            old_name='ID_oggetto',
            new_name='id_oggetto',
        ),
        migrations.RenameField(
            model_name='model_is_autore_documento_fonte_of',
            old_name='ID_soggetto',
            new_name='id_soggetto',
        ),
        migrations.RenameField(
            model_name='model_is_commento_entry_of',
            old_name='ID_oggetto',
            new_name='id_oggetto',
        ),
        migrations.RenameField(
            model_name='model_is_commento_entry_of',
            old_name='ID_soggetto',
            new_name='id_soggetto',
        ),
        migrations.RenameField(
            model_name='model_is_data_inserimento_entry_of',
            old_name='ID_oggetto',
            new_name='id_oggetto',
        ),
        migrations.RenameField(
            model_name='model_is_data_inserimento_entry_of',
            old_name='ID_soggetto',
            new_name='id_soggetto',
        ),
        migrations.RenameField(
            model_name='model_is_host_documento_fonte_of',
            old_name='ID_oggetto',
            new_name='id_oggetto',
        ),
        migrations.RenameField(
            model_name='model_is_host_documento_fonte_of',
            old_name='ID_soggetto',
            new_name='id_soggetto',
        ),
        migrations.RenameField(
            model_name='model_is_id_statico_entry_of',
            old_name='ID_oggetto',
            new_name='id_oggetto',
        ),
        migrations.RenameField(
            model_name='model_is_id_statico_entry_of',
            old_name='ID_soggetto',
            new_name='id_soggetto',
        ),
        migrations.RenameField(
            model_name='model_is_lemma_of',
            old_name='ID_oggetto',
            new_name='id_oggetto',
        ),
        migrations.RenameField(
            model_name='model_is_lemma_of',
            old_name='ID_soggetto',
            new_name='id_soggetto',
        ),
        migrations.RenameField(
            model_name='model_is_posizione_definizione_of',
            old_name='ID_oggetto',
            new_name='id_oggetto',
        ),
        migrations.RenameField(
            model_name='model_is_posizione_definizione_of',
            old_name='ID_soggetto',
            new_name='id_soggetto',
        ),
        migrations.RenameField(
            model_name='model_is_titolo_documento_fonte_of',
            old_name='ID_oggetto',
            new_name='id_oggetto',
        ),
        migrations.RenameField(
            model_name='model_is_titolo_documento_fonte_of',
            old_name='ID_soggetto',
            new_name='id_soggetto',
        ),
        migrations.RenameField(
            model_name='model_is_url_definizione_of',
            old_name='ID_oggetto',
            new_name='id_oggetto',
        ),
        migrations.RenameField(
            model_name='model_is_url_definizione_of',
            old_name='ID_soggetto',
            new_name='id_soggetto',
        ),
        migrations.RenameField(
            model_name='model_is_url_documento_fonte_of',
            old_name='ID_oggetto',
            new_name='id_oggetto',
        ),
        migrations.RenameField(
            model_name='model_is_url_documento_fonte_of',
            old_name='ID_soggetto',
            new_name='id_soggetto',
        ),
        migrations.RenameField(
            model_name='model_things',
            old_name='ID_Thing',
            new_name='id_thing',
        ),
        migrations.RenameField(
            model_name='model_things',
            old_name='Thing',
            new_name='thing',
        ),
    ]
