# Generated by Django 2.2.2 on 2020-01-30 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_metaglossario', '0046_auto_20191212_1514'),
    ]

    operations = [
        migrations.DeleteModel(
            name='displaying_terminology',
        ),
    ]
