# Generated by Django 2.2.2 on 2020-02-11 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_metaglossario', '0053_userprofileinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofileinfo',
            old_name='user_picture',
            new_name='profile_pic',
        ),
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='user_bio',
        ),
    ]
