# Generated by Django 2.2.2 on 2020-02-13 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_metaglossario', '0056_auto_20200211_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='user_bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='glossary_entry',
            name='Admin_approval_switch',
            field=models.CharField(choices=[('show', 'show'), ('hide', 'hide')], default='hide', max_length=30),
        ),
    ]
