# Generated by Django 2.2.2 on 2020-02-13 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_metaglossario', '0057_auto_20200213_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acquired_terminology',
            name='Admin_approval_switch',
            field=models.CharField(choices=[('show', 'show'), ('hide', 'hide')], default='hide', max_length=30),
        ),
        migrations.AlterField(
            model_name='prepared_terminology',
            name='Admin_approval_switch',
            field=models.CharField(choices=[('show', 'show'), ('hide', 'hide')], default='hide', max_length=30),
        ),
    ]
