# Generated by Django 2.2.2 on 2020-02-13 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_metaglossario', '0058_auto_20200213_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='glossary_file',
            name='Admin_approval_switch',
            field=models.CharField(choices=[('show', 'show'), ('hide', 'hide')], default='hide', max_length=30),
        ),
    ]
