# Generated by Django 2.2.2 on 2020-02-14 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_metaglossario', '0059_glossary_file_admin_approval_switch'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='glossary_file',
            options={'ordering': ['Data_inserimento_glossary', 'Glossary_file', 'Admin_approval_switch']},
        ),
    ]
