# Generated by Django 2.2.2 on 2020-02-17 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_metaglossario', '0060_auto_20200214_1320'),
    ]

    operations = [
        migrations.CreateModel(
            name='prova_oggetto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oggetto', models.CharField(blank=True, max_length=256, null=True)),
                ('data_tempo_creazione', models.DateTimeField(auto_now_add=True)),
                ('Id_automatico', models.CharField(default='ITCH<django.db.models.fields.DateTimeField>', max_length=256)),
            ],
        ),
    ]
