# Generated by Django 2.2.2 on 2020-02-17 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_metaglossario', '0061_prova_oggetto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prova_oggetto',
            name='data_tempo_creazione',
        ),
        migrations.AlterField(
            model_name='prova_oggetto',
            name='Id_automatico',
            field=models.CharField(default='ITCH15819356873781660', max_length=256),
        ),
    ]
