# Generated by Django 2.2.2 on 2020-02-17 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_metaglossario', '0062_auto_20200217_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prova_oggetto',
            name='Id_automatico',
            field=models.CharField(default='ITCH15819359702461204', max_length=256),
        ),
    ]
