# Generated by Django 2.2.2 on 2020-02-17 11:30

import app_metaglossario.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_metaglossario', '0063_auto_20200217_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prova_oggetto',
            name='Id_automatico',
            field=models.CharField(default=app_metaglossario.models.return_timestamped_id, max_length=256, unique=True),
        ),
    ]
