# Generated by Django 2.2.2 on 2020-02-17 11:54

import app_metaglossario.algoritmi_processing.script_ausiliari
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_metaglossario', '0064_auto_20200217_1230'),
    ]

    operations = [
        migrations.DeleteModel(
            name='prova_oggetto',
        ),
        migrations.AlterField(
            model_name='acquired_terminology',
            name='Id_statico_entry',
            field=models.CharField(default=app_metaglossario.algoritmi_processing.script_ausiliari.return_timestamped_id, max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='glossary_entry',
            name='Id_statico_entry',
            field=models.CharField(default=app_metaglossario.algoritmi_processing.script_ausiliari.return_timestamped_id, max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='prepared_terminology',
            name='Id_statico_entry',
            field=models.CharField(default=app_metaglossario.algoritmi_processing.script_ausiliari.return_timestamped_id, max_length=256, unique=True),
        ),
    ]
